# Generated by Django 4.1.5 on 2023-05-03 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_cartitem_basket_alter_cartitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coment', models.TextField(blank=True, null=True, verbose_name='Коментарий пользователя')),
                ('rate', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Not Good'), (3, 'Middle'), (4, 'Good'), (5, 'Very Good')])),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
