# Generated by Django 4.1.5 on 2023-05-04 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_categories'),
        ('users', '0003_userreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.product'),
            preserve_default=False,
        ),
    ]
