# Generated by Django 4.1.5 on 2023-06-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories_en',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories_ru',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_category', to='shop.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Product discription'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Product discription'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Product name'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Product name'),
        ),
    ]
