# Generated by Django 4.1.5 on 2023-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_categories_en_product_categories_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttags',
            name='tag_name_en',
            field=models.CharField(max_length=30, null=True, verbose_name='Product tags'),
        ),
        migrations.AddField(
            model_name='producttags',
            name='tag_name_ru',
            field=models.CharField(max_length=30, null=True, verbose_name='Product tags'),
        ),
    ]
